name: Python CI/CD
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install fastapi httpx sqlalchemy pydantic pytest flake8 black isort aiosqlite
    - run: |
        echo "Flake8:"
        flake8 . --max-line-length=200 --ignore=E501,E302
    - run: |
        echo "Black:"
        black --check . --line-length=200 --diff || exit 0
    - run: |
        echo "Isort:"
        isort . --check-only --line-length=200 || exit 0
    - run: |
        echo "Pytest:"
        pytest tests.py -v || exit 0
